version: '2'
volumes:
  {{ .Stack.Name }}-gitlab-app-data:
    driver: ${volumedriver}
  {{ .Stack.Name }}-gitlab-log-data:
    driver: ${volumedriver}
  {{ .Stack.Name }}-gitlab-conf-files:
    driver: ${volumedriver}

services:
  gitlab-server:
    ports:
    {{- if ne .Values.ssh_port "" }}
    - ${ssh_port}:22/tcp
    {{- else }}
    - 22/tcp
    {{- end }}
    - 80/tcp
    - 443/tcp
    labels:
      io.rancher.container.hostname_override: container_name
    image: gitlab/gitlab-ce:9.5.10-ce.0
    volumes:
      - {{ .Stack.Name }}-gitlab-app-data:/var/opt/gitlab
      - {{ .Stack.Name }}-gitlab-log-data:/var/log/gitlab
      - {{ .Stack.Name }}-gitlab-conf-files:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'
        registry_external_url '${gitlab_omnipus_prefix}${registry_gitlab_hostname}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${ssh_port}

  letsencrypt:
    image: janeczku/rancher-letsencrypt:v0.4.0
    environment:
      API_VERSION: Production
      AWS_ACCESS_KEY: ''
      AWS_SECRET_KEY: ''
      CERT_NAME: ${gitlab_hostname}
      CLOUDFLARE_EMAIL: ''
      CLOUDFLARE_KEY: ''
      DNSIMPLE_EMAIL: ''
      DNSIMPLE_KEY: ''
      DOMAINS: ${gitlab_hostname},${registry_gitlab_hostname}
      DO_ACCESS_TOKEN: ''
      DYN_CUSTOMER_NAME: ''
      DYN_PASSWORD: ''
      DYN_USER_NAME: ''
      EMAIL: hostmaster@banate.de
      EULA: 'Yes'
      GANDI_API_KEY: ''
      OVH_APPLICATION_KEY: ''
      OVH_APPLICATION_SECRET: ''
      OVH_CONSUMER_KEY: ''
      PROVIDER: HTTP
      PUBLIC_KEY_TYPE: RSA-2048
      RENEWAL_TIME: '12'
      VULTR_API_KEY: ''
    volumes:
      - {{ .Stack.Name }}-lets-encrypt:/etc/letsencrypt
    labels:
      io.rancher.container.agent.role: environment
      io.rancher.container.create_agent: 'true'

  LB:
    image: rancher/lb-service-haproxy:v0.5.9
    expose:
      - 443:443/tcp
      - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
