name: CloudCommander
description: |
  Cloud Commander orthodox web file manager with console and editor. Will help you manage the server and work with files, directories and programs in browser from any computer, mobile or tablet.
version: v0.1
category: Filemanager
