dokuwiki:
  ports:
  - 80/tcp
  labels:
    io.rancher.sidekicks: dokuwiki-data
  image: mprasil/dokuwiki
  volumes_from:
  - dokuwiki-data

dokuwiki-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  image: mprasil/dokuwiki