dokuwiki:
  ports:
  - 80/tcp
  labels:
    io.rancher.sidekicks: dokuwiki-data
  image: mprasil/dokuwiki:2015-08-10a
  volumes_from:
  - dokuwiki-data

dokuwiki-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  image: mprasil/dokuwiki:2015-08-10a
  volumes:
  - /dokuwiki/data/
  - /dokuwiki/lib/plugins/
  - /dokuwiki/conf/
  - /dokuwiki/lib/tpl/
  - /var/log/