dokuwiki:
  ports:
  - 80/tcp
  labels:
    io.rancher.sidekicks: dokuwiki-data
  image: istepanov/dokuwiki
  volumes_from:
  - dokuwiki-data

dokuwiki-data:
  entrypoint:
  - /bin/true
  image: istepanov/dokuwiki