.catalog:
  name: Dokuwiki
  version: 2015-08-10a
  description: |
    Dokuwiki is a free wiki software
  minimum_rancher_version: v0.56.0
  maintainer: "Leonard Frank <dev@leonardfrank.de>"
  uuid: dokuwiki-0

dokuwiki:
  scale: 1
  retain_ip: true
    health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

dokuwiki-data:
  scale: 1
  retain_ip: true
