
version: '2'

services:

  front:
    image: mailu/nginx:$VERSION
    restart: always
    environment:
      - ROOT=${ROOT}
      - VERSION=${VERSION}
      - SECRET_KEY=${SECRET_KEY}
      - BIND_ADDRESS4=${BIND_ADDRESS4}
      - BIND_ADDRESS6=${BIND_ADDRESS6}
      - DOMAIN=${DOMAIN}
      - HOSTNAMES=${HOSTNAMES}
      - POSTMASTER=${POSTMASTER}
      - TLS_FLAVOR=${TLS_FLAVOR}
      - AUTH_RATELIMIT=${AUTH_RATELIMIT}
      - DISABLE_STATISTICS=${DISABLE_STATISTICS}
      - ADMIN=${ADMIN}
      - WEBMAIL=${WEBMAIL}
      - WEBDAV=${WEBDAV}
      - ANTIVIRUS=${ANTIVIRUS}
      - MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT}
      - RELAYNETS=${RELAYNETS}
      - RELAYHOST=${RELAYHOST}
      - FETCHMAIL_DELAY=${FETCHMAIL_DELAY}
      - RECIPIENT_DELIMITER=${RECIPIENT_DELIMITER}
      - DMARC_RUA=${DMARC_RUA}
      - DMARC_RUF=${DMARC_RUF}
      - WEB_ADMIN=${WEB_ADMIN}
      - WEB_WEBMAIL=${WEB_WEBMAIL}
      - SITENAME=${SITENAME}
      - WEBSITE=${WEBSITE}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - PASSWORD_SCHEME=${PASSWORD_SCHEME}
    ports:
    - "$BIND_ADDRESS4:80:80"
    - "$BIND_ADDRESS4:443:443"
    - "$BIND_ADDRESS4:110:110"
    - "$BIND_ADDRESS4:143:143"
    - "$BIND_ADDRESS4:993:993"
    - "$BIND_ADDRESS4:995:995"
    - "$BIND_ADDRESS4:25:25"
    - "$BIND_ADDRESS4:465:465"
    - "$BIND_ADDRESS4:587:587"
    - "$BIND_ADDRESS6:80:80"
    - "$BIND_ADDRESS6:443:443"
    - "$BIND_ADDRESS6:110:110"
    - "$BIND_ADDRESS6:143:143"
    - "$BIND_ADDRESS6:993:993"
    - "$BIND_ADDRESS6:995:995"
    - "$BIND_ADDRESS6:25:25"
    - "$BIND_ADDRESS6:465:465"
    - "$BIND_ADDRESS6:587:587"
    volumes:
      - "$ROOT/certs:/certs"

  redis:
    image: redis:latest
    restart: always
    volumes:
      - "$ROOT/redis:/data"

  imap:
    image: mailu/dovecot:$VERSION
    restart: always
    environment:
      - ROOT=${ROOT}
      - VERSION=${VERSION}
      - SECRET_KEY=${SECRET_KEY}
      - BIND_ADDRESS4=${BIND_ADDRESS4}
      - BIND_ADDRESS6=${BIND_ADDRESS6}
      - DOMAIN=${DOMAIN}
      - HOSTNAMES=${HOSTNAMES}
      - POSTMASTER=${POSTMASTER}
      - TLS_FLAVOR=${TLS_FLAVOR}
      - AUTH_RATELIMIT=${AUTH_RATELIMIT}
      - DISABLE_STATISTICS=${DISABLE_STATISTICS}
      - ADMIN=${ADMIN}
      - WEBMAIL=${WEBMAIL}
      - WEBDAV=${WEBDAV}
      - ANTIVIRUS=${ANTIVIRUS}
      - MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT}
      - RELAYNETS=${RELAYNETS}
      - RELAYHOST=${RELAYHOST}
      - FETCHMAIL_DELAY=${FETCHMAIL_DELAY}
      - RECIPIENT_DELIMITER=${RECIPIENT_DELIMITER}
      - DMARC_RUA=${DMARC_RUA}
      - DMARC_RUF=${DMARC_RUF}
      - WEB_ADMIN=${WEB_ADMIN}
      - WEB_WEBMAIL=${WEB_WEBMAIL}
      - SITENAME=${SITENAME}
      - WEBSITE=${WEBSITE}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - PASSWORD_SCHEME=${PASSWORD_SCHEME}
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/mail:/mail"
      - "$ROOT/overrides:/overrides"

  smtp:
    image: mailu/postfix:$VERSION
    restart: always
    environment:
      - ROOT=${ROOT}
      - VERSION=${VERSION}
      - SECRET_KEY=${SECRET_KEY}
      - BIND_ADDRESS4=${BIND_ADDRESS4}
      - BIND_ADDRESS6=${BIND_ADDRESS6}
      - DOMAIN=${DOMAIN}
      - HOSTNAMES=${HOSTNAMES}
      - POSTMASTER=${POSTMASTER}
      - TLS_FLAVOR=${TLS_FLAVOR}
      - AUTH_RATELIMIT=${AUTH_RATELIMIT}
      - DISABLE_STATISTICS=${DISABLE_STATISTICS}
      - ADMIN=${ADMIN}
      - WEBMAIL=${WEBMAIL}
      - WEBDAV=${WEBDAV}
      - ANTIVIRUS=${ANTIVIRUS}
      - MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT}
      - RELAYNETS=${RELAYNETS}
      - RELAYHOST=${RELAYHOST}
      - FETCHMAIL_DELAY=${FETCHMAIL_DELAY}
      - RECIPIENT_DELIMITER=${RECIPIENT_DELIMITER}
      - DMARC_RUA=${DMARC_RUA}
      - DMARC_RUF=${DMARC_RUF}
      - WEB_ADMIN=${WEB_ADMIN}
      - WEB_WEBMAIL=${WEB_WEBMAIL}
      - SITENAME=${SITENAME}
      - WEBSITE=${WEBSITE}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - PASSWORD_SCHEME=${PASSWORD_SCHEME}
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/overrides:/overrides"

  antispam:
    image: mailu/rspamd:$VERSION
    restart: always
    environment:
      - ROOT=${ROOT}
      - VERSION=${VERSION}
      - SECRET_KEY=${SECRET_KEY}
      - BIND_ADDRESS4=${BIND_ADDRESS4}
      - BIND_ADDRESS6=${BIND_ADDRESS6}
      - DOMAIN=${DOMAIN}
      - HOSTNAMES=${HOSTNAMES}
      - POSTMASTER=${POSTMASTER}
      - TLS_FLAVOR=${TLS_FLAVOR}
      - AUTH_RATELIMIT=${AUTH_RATELIMIT}
      - DISABLE_STATISTICS=${DISABLE_STATISTICS}
      - ADMIN=${ADMIN}
      - WEBMAIL=${WEBMAIL}
      - WEBDAV=${WEBDAV}
      - ANTIVIRUS=${ANTIVIRUS}
      - MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT}
      - RELAYNETS=${RELAYNETS}
      - RELAYHOST=${RELAYHOST}
      - FETCHMAIL_DELAY=${FETCHMAIL_DELAY}
      - RECIPIENT_DELIMITER=${RECIPIENT_DELIMITER}
      - DMARC_RUA=${DMARC_RUA}
      - DMARC_RUF=${DMARC_RUF}
      - WEB_ADMIN=${WEB_ADMIN}
      - WEB_WEBMAIL=${WEB_WEBMAIL}
      - SITENAME=${SITENAME}
      - WEBSITE=${WEBSITE}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - PASSWORD_SCHEME=${PASSWORD_SCHEME}
    volumes:
      - "$ROOT/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d"

  antivirus:
    image: mailu/$ANTIVIRUS:$VERSION
    restart: always
    environment:
      - ROOT=${ROOT}
      - VERSION=${VERSION}
      - SECRET_KEY=${SECRET_KEY}
      - BIND_ADDRESS4=${BIND_ADDRESS4}
      - BIND_ADDRESS6=${BIND_ADDRESS6}
      - DOMAIN=${DOMAIN}
      - HOSTNAMES=${HOSTNAMES}
      - POSTMASTER=${POSTMASTER}
      - TLS_FLAVOR=${TLS_FLAVOR}
      - AUTH_RATELIMIT=${AUTH_RATELIMIT}
      - DISABLE_STATISTICS=${DISABLE_STATISTICS}
      - ADMIN=${ADMIN}
      - WEBMAIL=${WEBMAIL}
      - WEBDAV=${WEBDAV}
      - ANTIVIRUS=${ANTIVIRUS}
      - MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT}
      - RELAYNETS=${RELAYNETS}
      - RELAYHOST=${RELAYHOST}
      - FETCHMAIL_DELAY=${FETCHMAIL_DELAY}
      - RECIPIENT_DELIMITER=${RECIPIENT_DELIMITER}
      - DMARC_RUA=${DMARC_RUA}
      - DMARC_RUF=${DMARC_RUF}
      - WEB_ADMIN=${WEB_ADMIN}
      - WEB_WEBMAIL=${WEB_WEBMAIL}
      - SITENAME=${SITENAME}
      - WEBSITE=${WEBSITE}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - PASSWORD_SCHEME=${PASSWORD_SCHEME}
    volumes:
      - "$ROOT/filter:/data"

  webdav:
    image: mailu/$WEBDAV:$VERSION
    restart: always
    environment:
      - ROOT=${ROOT}
      - VERSION=${VERSION}
      - SECRET_KEY=${SECRET_KEY}
      - BIND_ADDRESS4=${BIND_ADDRESS4}
      - BIND_ADDRESS6=${BIND_ADDRESS6}
      - DOMAIN=${DOMAIN}
      - HOSTNAMES=${HOSTNAMES}
      - POSTMASTER=${POSTMASTER}
      - TLS_FLAVOR=${TLS_FLAVOR}
      - AUTH_RATELIMIT=${AUTH_RATELIMIT}
      - DISABLE_STATISTICS=${DISABLE_STATISTICS}
      - ADMIN=${ADMIN}
      - WEBMAIL=${WEBMAIL}
      - WEBDAV=${WEBDAV}
      - ANTIVIRUS=${ANTIVIRUS}
      - MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT}
      - RELAYNETS=${RELAYNETS}
      - RELAYHOST=${RELAYHOST}
      - FETCHMAIL_DELAY=${FETCHMAIL_DELAY}
      - RECIPIENT_DELIMITER=${RECIPIENT_DELIMITER}
      - DMARC_RUA=${DMARC_RUA}
      - DMARC_RUF=${DMARC_RUF}
      - WEB_ADMIN=${WEB_ADMIN}
      - WEB_WEBMAIL=${WEB_WEBMAIL}
      - SITENAME=${SITENAME}
      - WEBSITE=${WEBSITE}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - PASSWORD_SCHEME=${PASSWORD_SCHEME}
    volumes:
      - "$ROOT/dav:/data"

  admin:
    image: mailu/admin:$VERSION
    restart: always
    environment:
      - ROOT=${ROOT}
      - VERSION=${VERSION}
      - SECRET_KEY=${SECRET_KEY}
      - BIND_ADDRESS4=${BIND_ADDRESS4}
      - BIND_ADDRESS6=${BIND_ADDRESS6}
      - DOMAIN=${DOMAIN}
      - HOSTNAMES=${HOSTNAMES}
      - POSTMASTER=${POSTMASTER}
      - TLS_FLAVOR=${TLS_FLAVOR}
      - AUTH_RATELIMIT=${AUTH_RATELIMIT}
      - DISABLE_STATISTICS=${DISABLE_STATISTICS}
      - ADMIN=${ADMIN}
      - WEBMAIL=${WEBMAIL}
      - WEBDAV=${WEBDAV}
      - ANTIVIRUS=${ANTIVIRUS}
      - MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT}
      - RELAYNETS=${RELAYNETS}
      - RELAYHOST=${RELAYHOST}
      - FETCHMAIL_DELAY=${FETCHMAIL_DELAY}
      - RECIPIENT_DELIMITER=${RECIPIENT_DELIMITER}
      - DMARC_RUA=${DMARC_RUA}
      - DMARC_RUF=${DMARC_RUF}
      - WEB_ADMIN=${WEB_ADMIN}
      - WEB_WEBMAIL=${WEB_WEBMAIL}
      - SITENAME=${SITENAME}
      - WEBSITE=${WEBSITE}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - PASSWORD_SCHEME=${PASSWORD_SCHEME}
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/dkim:/dkim"
      - /var/run/docker.sock:/var/run/docker.sock:ro

  webmail:
    image: "mailu/$WEBMAIL:$VERSION"
    restart: always
    environment:
      - ROOT=${ROOT}
      - VERSION=${VERSION}
      - SECRET_KEY=${SECRET_KEY}
      - BIND_ADDRESS4=${BIND_ADDRESS4}
      - BIND_ADDRESS6=${BIND_ADDRESS6}
      - DOMAIN=${DOMAIN}
      - HOSTNAMES=${HOSTNAMES}
      - POSTMASTER=${POSTMASTER}
      - TLS_FLAVOR=${TLS_FLAVOR}
      - AUTH_RATELIMIT=${AUTH_RATELIMIT}
      - DISABLE_STATISTICS=${DISABLE_STATISTICS}
      - ADMIN=${ADMIN}
      - WEBMAIL=${WEBMAIL}
      - WEBDAV=${WEBDAV}
      - ANTIVIRUS=${ANTIVIRUS}
      - MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT}
      - RELAYNETS=${RELAYNETS}
      - RELAYHOST=${RELAYHOST}
      - FETCHMAIL_DELAY=${FETCHMAIL_DELAY}
      - RECIPIENT_DELIMITER=${RECIPIENT_DELIMITER}
      - DMARC_RUA=${DMARC_RUA}
      - DMARC_RUF=${DMARC_RUF}
      - WEB_ADMIN=${WEB_ADMIN}
      - WEB_WEBMAIL=${WEB_WEBMAIL}
      - SITENAME=${SITENAME}
      - WEBSITE=${WEBSITE}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - PASSWORD_SCHEME=${PASSWORD_SCHEME}
    volumes:
      - "$ROOT/webmail:/data"

  fetchmail:
    image: mailu/fetchmail:$VERSION
    restart: always
    environment:
      - ROOT=${ROOT}
      - VERSION=${VERSION}
      - SECRET_KEY=${SECRET_KEY}
      - BIND_ADDRESS4=${BIND_ADDRESS4}
      - BIND_ADDRESS6=${BIND_ADDRESS6}
      - DOMAIN=${DOMAIN}
      - HOSTNAMES=${HOSTNAMES}
      - POSTMASTER=${POSTMASTER}
      - TLS_FLAVOR=${TLS_FLAVOR}
      - AUTH_RATELIMIT=${AUTH_RATELIMIT}
      - DISABLE_STATISTICS=${DISABLE_STATISTICS}
      - ADMIN=${ADMIN}
      - WEBMAIL=${WEBMAIL}
      - WEBDAV=${WEBDAV}
      - ANTIVIRUS=${ANTIVIRUS}
      - MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT}
      - RELAYNETS=${RELAYNETS}
      - RELAYHOST=${RELAYHOST}
      - FETCHMAIL_DELAY=${FETCHMAIL_DELAY}
      - RECIPIENT_DELIMITER=${RECIPIENT_DELIMITER}
      - DMARC_RUA=${DMARC_RUA}
      - DMARC_RUF=${DMARC_RUF}
      - WEB_ADMIN=${WEB_ADMIN}
      - WEB_WEBMAIL=${WEB_WEBMAIL}
      - SITENAME=${SITENAME}
      - WEBSITE=${WEBSITE}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - PASSWORD_SCHEME=${PASSWORD_SCHEME}
    volumes:
      - "$ROOT/data:/data"
