version: '2'
services:
    wordpress:
        image: wordpress
        links:
          - db:mysql
        ports:
          - 80/tcp
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: example
    {{- if ne .Values.DOMAIN "" }}
    LB:
        image: rancher/lb-service-haproxy:v0.7.9
        expose:
            - 443:443/tcp
            - 80:80/tcp
        labels:
            io.rancher.container.agent.role: environmentAdmin
            io.rancher.container.create_agent: 'true'
        scale: 1
        start_on_create: true
        lb_config:
            certs: []
            port_rules:
                -
                    hostname: ${DOMAIN}
                    path: /.well-known/acme-challenge
                    priority: 1
                    protocol: http
                    service: letsencrypt
                    source_port: 443
                    target_port: 80
                -
                    hostname: ${DOMAIN}
                    path: /.well-known/acme-challenge
                    priority: 2
                    protocol: http
                    service: letsencrypt
                    source_port: 80
                    target_port: 80
                -
                    hostname: ${DOMAIN}
                    priority: 3
                    protocol: http
                    service: Network/https-redirect
                    source_port: 80
                    target_port: 80
                -
                    hostname: ${DOMAIN}
                    priority: 4
                    protocol: http
                    service: wordpress
                    source_port: 443
                    target_port: 80
                -
                    priority: 5
                    protocol: http
                    service: Network/404
                    source_port: 443
                    target_port: 80
                -
                    priority: 6
                    protocol: http
                    service: Network/404
                    source_port: 80
                    target_port: 80
        health_check:
            healthy_threshold: 2
            response_timeout: 2000
            port: 42
            unhealthy_threshold: 3
            interval: 2000
            strategy: recreate
    letsencrypt:
        image: janeczku/rancher-letsencrypt:v0.5.0
        environment:
            API_VERSION: Production
            AWS_ACCESS_KEY: ''
            AWS_SECRET_KEY: ''
            CERT_NAME: ${DOMAIN}
            CLOUDFLARE_EMAIL: ''
            CLOUDFLARE_KEY: ''
            DNSIMPLE_EMAIL: ''
            DNSIMPLE_KEY: ''
            DOMAINS: ${DOMAIN}
            DO_ACCESS_TOKEN: ''
            DYN_CUSTOMER_NAME: ''
            DYN_PASSWORD: ''
            DYN_USER_NAME: ''
            EMAIL: ${LETSENCRYPT_MAIL}
            EULA: 'Yes'
            GANDI_API_KEY: ''
            OVH_APPLICATION_KEY: ''
            OVH_APPLICATION_SECRET: ''
            OVH_CONSUMER_KEY: ''
            PROVIDER: HTTP
            PUBLIC_KEY_TYPE: RSA-2048
            RENEWAL_TIME: '12'
            VULTR_API_KEY: ''
        volumes:
            - lets-encrypt:/etc/letsencrypt
        labels:
            io.rancher.container.agent.role: environment
            io.rancher.container.create_agent: 'true'
        scale: 1
        start_on_create: false
    {{- end }}
{{- if ne .Values.DOMAIN "" }}
volumes:
    lets-encrypt:
        external: true
        driver: 'null'
{{- end }}
